version: '3.1'

services:

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        depends_on:
            - db
        ports:
            - 8888:8080
    phpmyadmin:
        image: phpmyadmin
        restart: always
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=root
        ports:
            - 8080:80
volumes:
    db-data: ~

# version: '3.8'

# services:
#     database:
#         image: mysql:5.7
#         ports:
#             - 3306:3306
#         environment:
#             - MYSQL_DATABASE=${DB_DATABASE}
#             - MYSQL_USER=${DB_USERNAME}
#             - MYSQL_PASSWORD=${DB_PASSWORD}
#             - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
#         # volumes:
#         #     - db-data:/var/lib/mysql
#     phpmyadmin:
#         image: phpmyadmin
#         restart: always
#         environment:
#             - PMA_HOST=database
#             - PMA_USER=root
#             - PMA_PASSWORD=root
#         ports:
#             - 8080:80

# volumes:
#     db-data: ~

# version: '3.8'
# services:
#   db:
#     image: mysql:8.0
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: test_db
#     ports:
#       - "3308:3306"
#   phpmyadmin:
#     image: phpmyadmin
#     restart: always
#     environment:
#       PMA_HOST: db
#       PMA_USER: root
#       PMA_PASSWORD: root
#     ports:
#       - "8080:80"
